name: CI
on: [push, pull_request]
jobs:
  test:
    name: Mininet Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out Mininet source
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Mininet and dependencies
        run: |
          sudo util/install.sh -n  # -n for minimal install
          sudo make mnexec

      - name: Run code checks
        run: |
          make codecheck
          make errcheck

      - name: Run basic tests
        run: |
          make test

      - name: Run comprehensive tests
        run: |
          make slowtest